name: Flutter CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
    - name: Upgrade Flutter
      run: flutter upgrade

    - name: Install dependencies
      run: flutter pub get

    - name: Clear Flutter Cache
      run: flutter clean

    - name: Run Tests
      run: flutter test

    